{
  "formatVersion": "1.1",
  "component": {
    "group": "ru.kochkaev",
    "module": "seasons-api",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "seasons-api-1.0-SNAPSHOT.jar",
          "url": "seasons-api-1.0-SNAPSHOT.jar",
          "size": 77384,
          "sha512": "b97537bf9baa5f681d2e72ae5e912ffb3adcbdc13fd95eb9a0ef598c32dfdf608a86a5954c759c9f9e534a388c47fcf7964fa8fa61b1f51b85978e357a32dbe1",
          "sha256": "cc5eebf608af3c2f73e7a0058b2dc15a8298dff05e204cc4085f5066e989409f",
          "sha1": "e527d7a7f63390df6c878dc2b5b897e1fa5a1c83",
          "md5": "1978b3db2a1fc1c0358a4bb2e5019f9e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.0"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.100.7+1.21"
          }
        }
      ],
      "files": [
        {
          "name": "seasons-api-1.0-SNAPSHOT.jar",
          "url": "seasons-api-1.0-SNAPSHOT.jar",
          "size": 77384,
          "sha512": "b97537bf9baa5f681d2e72ae5e912ffb3adcbdc13fd95eb9a0ef598c32dfdf608a86a5954c759c9f9e534a388c47fcf7964fa8fa61b1f51b85978e357a32dbe1",
          "sha256": "cc5eebf608af3c2f73e7a0058b2dc15a8298dff05e204cc4085f5066e989409f",
          "sha1": "e527d7a7f63390df6c878dc2b5b897e1fa5a1c83",
          "md5": "1978b3db2a1fc1c0358a4bb2e5019f9e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "seasons-api-1.0-SNAPSHOT-sources.jar",
          "url": "seasons-api-1.0-SNAPSHOT-sources.jar",
          "size": 52407,
          "sha512": "fdf9cb45b9a0c2b44706c2c591c980f7afea4b1a5124dccfad0474ae52ca6b9318adf1c0cf7c881e527635348ea3a9c9907abdcdc2252ffb3ae211854fd14aca",
          "sha256": "7ef93b28fef9b46b21dc182d0277da8d08afe7877e3ac9bbf10a47f1ba4fc22d",
          "sha1": "504199a747eea115b1b564fca40d18fd04c4c265",
          "md5": "aacb0365567abaa0ab60f53276946944"
        }
      ]
    }
  ]
}
